# Generated by Django 3.2.18 on 2023-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select1_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='select2_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
