# Generated by Django 3.2.18 on 2023-04-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230421_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select1_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='select2_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
